title: 😌 mentalhealth.day
author:
  name: Johhn McCall

# The `>` after `description:` means to ignore line-breaks until next key.
# If you want to omit the line-break after the end of text, use `>-` instead.
description: >
  Share this site as your status, out of office email, or on social media when you take a self-care day to normalize and destigmatize mental health.

# Build settings

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Theme-specific settings

minima:
  # Minima date format.
  # Refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this.
  #
  # date_format: "%b %-d, %Y"

  # Generate social links in footer.
  #
    social_links:
  #   - { platform: devto,          user_url: "https://dev.to/jekyll" }
  #   - { platform: dribbble,       user_url: "https://dribbble.com/jekyll" }
  #   - { platform: facebook,       user_url: "https://www.facebook.com/jekyll" }
      - { platform: github,         user_url: "https://github.com/lowlydba/mentalhealth.day" }
  #   - { platform: google_scholar, user_url: "https://scholar.google.com/citations?user=qc6CJjYAAAAJ" }
  #   - { platform: keybase,        user_url: "https://keybase.io/jekyll" }
      - { platform: linkedin,       user_url: "https://www.linkedin.com/sharing/share-offsite/?url=https://mentalhealth.day" }
  #   - { platform: stackoverflow,  user_url: "https://stackoverflow.com/users/1234567/jekyll" }
  #   - { platform: telegram,       user_url: "https://t.me/jekyll" }
      - { platform: twitter,        user_url: "https://twitter.com/intent/tweet?text=I%27m%20taking%20a%20mentalhealth.day" }
# If you want to link only specific pages in your header, uncomment this and add the path to the pages in
# order as they should show up.
#
# header_pages:
#   - about.md

# Set to `true` to show excerpts on the homepage.
#
# show_excerpts: false
